services:
  minecraft:
    image: 'itzg/minecraft-server:java25'
    hostname: minecraft
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: true
      TYPE: 'FABRIC'
      VERSION: '26.1'
      MEMORY: '12G'
      MAX_PLAYERS: 5
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 8
      DIFFICULTY: 'hard'
      SPAWN_PROTECTION: 0
      SYNC_CHUNK_WRITES: false
      RESOURCE_PACK: 'https://mcpacks.dev/pack/714187ba-c4d5-41ad-9a54-a3651d55fb42/download'
      RESOURCE_PACK_SHA1: '2bf3b604634d6fef6326f11c9476029cd3e0dbdf'
      RESOURCE_PACK_ENFORCE: true
      ENABLE_RCON: true
      ACCEPTS_TRANSFERS: true
      MANAGEMENT_SERVER_ENABLED: true
      MANAGEMENT_SERVER_HOST: minecraft
      MANAGEMENT_SERVER_ALLOWED_ORIGINS: picolimbo
      MANAGEMENT_SERVER_PORT: 25556
      MANAGEMENT_SERVER_TLS_ENABLED: false
      DATAPACKS: 'https://cdn.modrinth.com/data/XW3ki6HN/versions/U3pcPLSy/Bingo%20datapack%201.21.11.zip'
      MODS_FILE: '/extras/mods.txt'
      JVM_XX_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI'
    volumes:
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./config:/config
    env_file: .env.secrets
    tty: true
    stdin_open: true
    restart: unless-stopped
  picolimbo:
    image: ghcr.io/cadenkriese/picolimbo:cookie-packets
    hostname: picolimbo
    container_name: picolimbo
    env_file: .env.secrets
    restart: unless-stopped
    ports:
      - 25585:25585
    volumes:
      - ./limbo/config.toml:/usr/src/app/server.toml
      - ./limbo/hypixel.schem:/usr/src/app/hypixel.schem
