services:
  minecraft:
    image: 'itzg/minecraft-server:java21-graalvm'
    hostname: minecraft
    container_name: minecraft
    ports:
      - 25565:25565     # Minecraft
      - 25575:25575     # Rcon
    environment:
      EULA: true
      TYPE: 'FABRIC'
      VERSION: '1.21.11'
      MEMORY: '12G'
      MAX_PLAYERS: 5
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 8
      PAUSE_WHEN_EMPTY_SECONDS: 60
      DIFFICULTY: 'hard'
      HARDCORE: true
      SPAWN_PROTECTION: 0
      ENABLE_RCON: true
      SYNC_CHUNK_WRITES: false
      ENFORCE_SECURE_PROFILE: true
      OVERRIDE_SERVER_PROPERTIES: true
      MODS_FILE: '/extras/mods.txt'
      JVM_XX_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI'
      JVM_DD_OPTS: '-Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise'
    volumes:
      - ./data:/data
      - ./mods.txt:/extras/mods.txt:ro
      - ./config:/config
    env_file: .env.secrets
    tty: true
    stdin_open: true
    restart: unless-stopped
  pico-limbo:
    image: ghcr.io/cadenkriese/picolimbo:cookie-packets
    container_name: picolimbo
    restart: unless-stopped
    ports:
      - 25585:25585
    volumes:
      - ./limbo/config.toml:/usr/src/app/server.toml
      - ./limbo/hypixel.schem:/usr/src/app/hypixel.schem